Url="https://id.en-courage.com/admin/users/search?"

#Authは変えないで
Auth="authenticity_token=xzvB/2M/LRSgrBVMg3GPe9UlD17ke9J0CXrySO/7c7o/aKvppZA6RQSg0XuJvZv3yZoyF4OTQins6X2kfq0PDg=="

#WriteType...detail=詳細時間かかる，light=データ少ないが早い,printData=登録数，理系数,同女，GEカズのみだす,updateSpreadSheet=エンターリストのスプレッシートに書き込み
WriteType="notMenter"

#出力ファイル
WriteFile="./enter.csv"

#Qs=クエリ，基本的に検索条件を変更する際に使用
  [[Qs]]
    Key="q[last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont]"
    Val=""
  [[Qs]]
    Key="&q[user_educational_last_educational_year_eq]"
    Val="2020"
  [[Qs]]
    Key="q[univ_name_or_graduate_name_cont]"
    Val="同志社"
  [[Qs]]
    Key="q[last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont]"
    Val=""
  [[Qs]]
    Key="q[last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont]"
    Val=""
  [[Qs]]
    Key="q[last_name_or_first_name_or_last_name_kana_or_first_name_kana_cont]"
    Val=""




